### ISSUE TITLE
The list of articles is not renewed

### ISSUE THREAD

**Issue by Acgsior** [starandtina/articles#1]
e.g.  `2017-08-07-how-do-we-normalize-state.md` can not be found at [https://starandtina.github.io/articles/](https://starandtina.github.io/articles/)

**Comment by starandtina** [comment]
是说的这个吗？http://fee.surge.sh/Tech/React/2017-08-07-how-do-we-normalize-state.html

**Comment by Acgsior** [comment]
是的 但是首页的列表上面没有显示这个呢

**Comment by starandtina** [comment]
@Acgsior 多谢反馈，也有对应链接的。

![image](https://user-images.githubusercontent.com/613990/44298906-cb4d7e80-a31e-11e8-856c-57ce3c994cc7.png)
